version: "3.9"

services:
  web:
    build: .
    command: gunicorn --workers 3 --timeout 120 youtube_downloader.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_NAME=yt_db
      - DB_USER=postgres
      - DB_PASSWORD=Money237__@
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=yt_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Money237__@
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  # Optional: Expose DB port for local access

volumes:
  postgres_data:
  static_volume:
  media_volume: